# This file was generated by GoReleaser. DO NOT EDIT.
cask "leggo" do
  name "leggo"
  desc "A command line background process orchestrator"
  homepage "https://github.com/andresrobam/leggo"
  version "0.5.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leggo"

  on_macos do
    on_intel do
      url "https://github.com/andresrobam/leggo/releases/download/v#{version}/leggo_Darwin_x86_64.tar.gz"
      sha256 "a11f60e5aafe7d19e47a79fa3f3fa3fcbb1701ebd9fb5c2931a44652d5a1d511"
    end
    on_arm do
      url "https://github.com/andresrobam/leggo/releases/download/v#{version}/leggo_Darwin_arm64.tar.gz"
      sha256 "b267a6fa5a6d5b65257a45c2be01276a35e1ad6db26f836145ad9bd807fb00e1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andresrobam/leggo/releases/download/v#{version}/leggo_Linux_x86_64.tar.gz"
      sha256 "eb1f57ba6f50c8c8521cdefb5859d06f4974144b7f5e8796924ceb2bcc488a77"
    end
    on_arm do
      url "https://github.com/andresrobam/leggo/releases/download/v#{version}/leggo_Linux_arm64.tar.gz"
      sha256 "a9839852b4edcb865874803974f49f0bb402a6e446b5633692ed12bf6b4ed821"
    end
  end

  # No zap stanza required
end
