# This file was generated by GoReleaser. DO NOT EDIT.
cask "leggo" do
  name "leggo"
  desc "A command line background process orchestrator"
  homepage "https://github.com/andresrobam/leggo"
  version "0.5.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leggo"

  on_macos do
    on_intel do
      url "https://github.com/andresrobam/leggo/releases/download/v#{version}/leggo_Darwin_x86_64.tar.gz"
      sha256 "165bf86bd2e48267ac5b94f62800b1af2f6e3c3041d05f0ff8457b545c14d99c"
    end
    on_arm do
      url "https://github.com/andresrobam/leggo/releases/download/v#{version}/leggo_Darwin_arm64.tar.gz"
      sha256 "00c91039df6a18f3b6b9bbb32566e04092a293b385042fa5a390c14ecfc24844"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andresrobam/leggo/releases/download/v#{version}/leggo_Linux_x86_64.tar.gz"
      sha256 "4196ca35362d75cfc34c0fd26c9fb64336d517b24c2a93271b1351127dd2d1d6"
    end
    on_arm do
      url "https://github.com/andresrobam/leggo/releases/download/v#{version}/leggo_Linux_arm64.tar.gz"
      sha256 "ab4ca575b21fa733e027063e1ac28862d923597227e8c323a731674503d4bf49"
    end
  end

  # No zap stanza required
end
