# This file was generated by GoReleaser. DO NOT EDIT.
cask "leggo" do
  name "leggo"
  desc "A command line background process orchestrator"
  homepage "https://github.com/andresrobam/leggo"
  version "0.6.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leggo"

  on_macos do
    on_intel do
      url "https://github.com/andresrobam/leggo/releases/download/v#{version}/leggo_Darwin_x86_64.tar.gz"
      sha256 "c141a0f0617c9f2b3453f74267b213f4ac63c48f59a6c1dfff88cb8677c367b1"
    end
    on_arm do
      url "https://github.com/andresrobam/leggo/releases/download/v#{version}/leggo_Darwin_arm64.tar.gz"
      sha256 "a7e385c95e6272384bd4c4b7464a7957816ab7688d25eade4fecb1373d4a1e04"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andresrobam/leggo/releases/download/v#{version}/leggo_Linux_x86_64.tar.gz"
      sha256 "752b3e1fd482e87c67a0299a229e923b00f376cca3b1f5eb640726cab5c3bd5d"
    end
    on_arm do
      url "https://github.com/andresrobam/leggo/releases/download/v#{version}/leggo_Linux_arm64.tar.gz"
      sha256 "82a80429f9a030662079d00d65ecf31068f3bf728cf0bcc5fd6877a5c0c47b8a"
    end
  end

  # No zap stanza required
end
